import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  /**
   * 编程学习
   */
  javascript: [{ type: 'autogenerated', dirName: 'learn/javascript' }],
  jquery: [{ type: 'autogenerated', dirName: 'learn/jquery' }],
  node: [{ type: 'autogenerated', dirName: 'learn/node' }],
  typescript: [{ type: 'autogenerated', dirName: 'learn/typescript' }],
  webpack: [{ type: 'autogenerated', dirName: 'learn/webpack' }],
  rxjs: [{ type: 'autogenerated', dirName: 'learn/rxjs' }],
  angular: [{ type: 'autogenerated', dirName: 'learn/angular' }],
  flutter: [{ type: 'autogenerated', dirName: 'learn/flutter' }],
  rust: [{ type: 'autogenerated', dirName: 'learn/rust' }],
  java: [{ type: 'autogenerated', dirName: 'learn/java' }],
  /**
   * 数据结构与算法
   */
  algorithm: [{ type: 'autogenerated', dirName: 'algorithm' }],
  /**
   * 设计模式
   */
  designMode: [{ type: 'autogenerated', dirName: 'design-mode' }],
  /**
   * DevOps专题
   */
  devops: [{ type: 'autogenerated', dirName: 'devops' }],
  /**
   * 操作系统
   */
  os: [{ type: 'autogenerated', dirName: 'os' }],
  /**
   * 计算机网络
   */
  network: [{ type: 'autogenerated', dirName: 'network' }],
  /**
   * 博客
   */
  blog: [{ type: 'autogenerated', dirName: 'blog' }],
  /**
   * 日常记录
   */
  daily: [{ type: 'autogenerated', dirName: 'daily' }],
};

export default sidebars;
