import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  /**
   * 前端学习笔记
   */
  javascript: [{ type: 'autogenerated', dirName: 'fe/javascript' }],
  jquery: [{ type: 'autogenerated', dirName: 'fe/jquery' }],
  node: [{ type: 'autogenerated', dirName: 'fe/node' }],
  typescript: [{ type: 'autogenerated', dirName: 'fe/typescript' }],
  webpack: [{ type: 'autogenerated', dirName: 'fe/webpack' }],
  rxjs: [{ type: 'autogenerated', dirName: 'fe/rxjs' }],
  angular: [{ type: 'autogenerated', dirName: 'fe/angular' }],
  flutter: [{ type: 'autogenerated', dirName: 'fe/flutter' }],
  /**
   * rust学习笔记
   */
  rust: [{ type: 'autogenerated', dirName: 'rust' }],
  /**
   * Java学习笔记
   */
  java: [{ type: 'autogenerated', dirName: 'java' }],
  /**
   * 博客
   */
  blog: [{ type: 'autogenerated', dirName: 'blog' }],
  /**
   * DevOps专题
   */
  devops: [{ type: 'autogenerated', dirName: 'devops' }],
  /**
   * 操作系统
   */
  os: [{ type: 'autogenerated', dirName: 'os' }],
  /**
   * 计算机网络
   */
  network: [{ type: 'autogenerated', dirName: 'network' }],
  /**
   * 日常记录
   */
  daily: [{ type: 'autogenerated', dirName: 'daily' }],
};

export default sidebars;
