import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

const sidebars: SidebarsConfig = {
  /**
   * 学习记录文档
   */
  // html: [{ type: 'autogenerated', dirName: 'notes/html' }],
  // css: [{ type: 'autogenerated', dirName: 'notes/css' }],
  // scss: [{ type: 'autogenerated', dirName: 'notes/scss' }],
  javascript: [{ type: 'autogenerated', dirName: 'learn/javascript' }],
  jquery: [{ type: 'autogenerated', dirName: 'learn/jquery' }],
  node: [{ type: 'autogenerated', dirName: 'learn/node' }],
  typescript: [{ type: 'autogenerated', dirName: 'learn/typescript' }],
  webpack: [{ type: 'autogenerated', dirName: 'learn/webpack' }],
  rxjs: [{ type: 'autogenerated', dirName: 'learn/rxjs' }],
  // react: [{ type: 'autogenerated', dirName: 'notes/react' }],
  angular: [{ type: 'autogenerated', dirName: 'learn/angular' }],
  // next: [{ type: 'autogenerated', dirName: 'notes/next' }],
  // flutter: [{ type: 'autogenerated', dirName: 'notes/flutter' }],
  network: [{ type: 'autogenerated', dirName: 'learn/network' }],
  /**
   * 博客
   */
  blog: [{ type: 'autogenerated', dirName: 'blog' }],
  /**
   * DevOps专题
   */
  devops: [{ type: 'autogenerated', dirName: 'devops' }],
  /**
   * 日常记录
   */
  daily: [{ type: 'autogenerated', dirName: 'daily' }],
};

export default sidebars;
